# Generated by Django 6.0.7 on 2026-08-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0003_alter_trainee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
