# Generated by Django 6.0.7 on 2026-07-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='name',
            field=models.CharField(default='python', max_length=50),
            preserve_default=False,
        ),
    ]
